In [18]:
from core.commodity import *
from core.database import *


commodity = 'gold'

db = Database(name='bdf')

cur = db.get_commodity(commodity)

In [19]:
pd.DataFrame(list(cur))

,_id,change,commodity,date,high,low,open,price,vol
0,5a8dbb5c160b3d175eb8fb76,0.0007,gold,2018-02-21T00:00:00Z,1335.2,1327.4,1332.2,1332.1,0.0
1,5a8dbb5c160b3d175eb8fb77,-0.0123,gold,2018-02-20T00:00:00Z,1354.0,1330.6,1350.2,1331.2,359380.0
2,5a8dbb5c160b3d175eb8fb78,-0.0020,gold,2018-02-19T00:00:00Z,1353.9,1347.4,1350.4,1347.8,0.0
3,5a8dbb5c160b3d175eb8fb79,-0.0042,gold,2018-02-18T00:00:00Z,1352.4,1349.7,1349.7,1350.5,0.0
4,5a8dbb5c160b3d175eb8fb7a,0.0007,gold,2018-02-16T00:00:00Z,1364.4,1347.3,1356.6,1356.2,230900.0
5,5a8dbb5c160b3d175eb8fb7b,-0.0020,gold,2018-02-15T00:00:00Z,1359.8,1350.8,1353.0,1355.3,274930.0
6,5a8dbb5c160b3d175eb8fb7c,0.0207,gold,2018-02-14T00:00:00Z,1358.6,1319.1,1331.9,1358.0,431720.0
7,5a8dbb5c160b3d175eb8fb7d,0.0030,gold,2018-02-13T00:00:00Z,1333.5,1323.7,1325.0,1330.4,201430.0
8,5a8dbb5c160b3d175eb8fb7e,0.0081,gold,2018-02-12T00:00:00Z,1330.0,1316.3,1317.1,1326.4,208070.0
9,5a8dbb5c160b3d175eb8fb7f,-0.0025,gold,2018-02-09T00:00:00Z,1325.0,1313.2,1321.0,1315.7,317670.0
10,5a8dbb5c160b3d175eb8fb80,0.0033,gold,2018-02-08T00:00:00Z,1324.5,1309.0,1320.7,1319.0,365930.0
11,5a8dbb5c160b3d175eb8fb81,-0.0112,gold,2018-02-07T00:00:00Z,1334.8,1313.5,1326.6,1314.6,351230.0
12,5a8dbb5c160b3d175eb8fb82,-0.0052,gold,2018-02-06T00:00:00Z,1349.3,1322.8,1343.1,1329.5,473350.0
13,5a8dbb5c160b3d175eb8fb83,-0.0006,gold,2018-02-05T00:00:00Z,1344.8,1331.6,1334.6,1336.5,305680.0
14,5a8dbb5c160b3d175eb8fb84,-0.0079,gold,2018-02-02T00:00:00Z,1353.3,1330.1,1352.2,1337.3,431410.0
15,5a8dbb5c160b3d175eb8fb85,0.0036,gold,2018-02-01T00:00:00Z,1354.3,1340.2,1348.2,1347.9,310500.0
16,5a8dbb5c160b3d175eb8fb86,0.0023,gold,2018-01-31T00:00:00Z,1351.0,1335.5,1341.8,1343.1,377140.0
17,5a8dbb5c160b3d175eb8fb87,-0.0038,gold,2018-01-30T00:00:00Z,1352.5,1337.5,1344.0,1340.0,412520.0
18,5a8dbb5c160b3d175eb8fb88,-0.0089,gold,2018-01-29T00:00:00Z,1356.3,1340.9,1353.7,1345.1,233760.0
19,5a8dbb5c160b3d175eb8fb89,-0.0079,gold,2018-01-26T00:00:00Z,1361.0,1348.6,1352.7,1357.2,142270.0
20,5a8dbb5c160b3d175eb8fb8a,0.0048,gold,2018-01-25T00:00:00Z,1370.5,1346.2,1362.7,1368.0,142580.0
21,5a8dbb5c160b3d175eb8fb8b,0.0147,gold,2018-01-24T00:00:00Z,1366.8,1344.1,1346.2,1361.4,159340.0
22,5a8dbb5c160b3d175eb8fb8c,0.0036,gold,2018-01-23T00:00:00Z,1346.6,1335.8,1338.4,1341.7,70400.0
23,5a8dbb5c160b3d175eb8fb8d,0.0029,gold,2018-01-22T00:00:00Z,1340.3,1332.9,1339.4,1336.9,104320.0

In [16]:
import datetime as dt

start_date = '2018-02-01'

dt.datetime.strptime(start_date, '%Y-%m-%d')

datetime.datetime(2018, 2, 1, 0, 0)